### ISSUE TITLE
Could you provide the implementation of other algorithms?

### ISSUE THREAD

**Issue by LZleejean** [Mike-Leo-Smith/Ensemble-Denoising#2]
This paper is such great work and evaluate so many existing algorithms.

But I found that some algorithms are not easy to reimplement. Therefore, could you provide your implementation, like RDFC?

**Comment by Mike-Leo-Smith** [comment]
Thank you. We did not reimplement RDFC but were using the release from the authors: http://cgg-zwicker.inf.unibe.ch/downloads/pg2013_code_data.zip

**Comment by Mike-Leo-Smith** [comment]
> Thank you. We did not reimplement RDFC but were using the release from the authors: http://cgg-zwicker.inf.unibe.ch/downloads/pg2013_code_data.zip

PS. I have checked the link again, and it seems to work but downloads very slowly (~10KB/s)... So you might need to send an email directly to the authors to request a copy.

**Comment by Mike-Leo-Smith** [comment]
Links for other work:

**Comment by Mike-Leo-Smith** [comment]
Links for other work:
KPCN: https://jannovak.info/publications/KPCN/index.html
MCGAN: http://adversarial.mcdenoising.org
NFOR: https://github.com/tunabrain/tungsten (implemented in Tungsten's denoiser module)
OIDN: https://github.com/OpenImageDenoise/oidn
OptiX: https://developer.nvidia.com/designworks/optix/download (integrated inside the OptiX Ray Tracing framework)

**Comment by LZleejean** [comment]
Thanks very much for your help.
