### ISSUE TITLE
Using weight channel 1 instead of 3.

### ISSUE THREAD

**Issue by qbhan** [Mike-Leo-Smith/Ensemble-Denoising#3]
I would like to also see the results of using weight channel of 1 applied to the pixell instead of weight channel of 3 applied to RGB channel each. I think a slight modification would do, but I cannot find which to change. Could you provide specific details on which part should I change to do so? Thank you in advance!

**Comment by Mike-Leo-Smith** [comment]
Hi, qbhan.

The weight channels of 3 are currently hardcoded in several places in the code, which might not be straightforward to modify.

Meanwhile, if you're just for testing and performance is not a concern, a simple hack on
https://github.com/Mike-Leo-Smith/Ensemble-Denoising/blob/becc55628dc93502fd1b04cc4fb80fd51daab9c0/src/solve.h#L161-L167
will do the trick (but at the cost of wasted computation).

Basic ideas: the weight-solving algorithm works on the three channels of the input images. If all the channels are identical, then the resulting weights are equivalent to solving for a single channel. Therefore, you may average the three channels of `I0A`, `I0B`, `IA`, and `IB` and convert them back to fake 3-channel images for the follow-up solving process:
```cpp
solve_weights_specialized(const cv::Mat &I0A_in, const cv::Mat &I0B_in,
                          const std::vector<cv::Mat> &IA_in,
                          const std::vector<cv::Mat> &IB_in,
                          Solver solver,
                          bool solve_full,
                          double beta = 0.0) {

    cv::Mat I0A, I0B, IA, IB;
    // convert input images to 1-channel
    cv::cvtColor(I0A_in, I0A, cv::COLOR_BGR2GRAY);
    cv::cvtColor(I0B_in, I0B, cv::COLOR_BGR2GRAY);
    cv::cvtColor(IA_in, IA, cv::COLOR_BGR2GRAY);
    cv::cvtColor(IB_in, IB, cv::COLOR_BGR2GRAY);
    // convert back to "fake" 3-channel images each with identical channels
    cv::cvtColor(I0A, I0A, cv::COLOR_GRAY2BGR);
    cv::cvtColor(I0B, I0B, cv::COLOR_GRAY2BGR);
    cv::cvtColor(IA, IA, cv::COLOR_GRAY2BGR);
    cv::cvtColor(IB, IB, cv::COLOR_GRAY2BGR);
```
